services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .docker/nginx/conf.d/:/etc/nginx/conf.d/
            - .docker/nginx/logs/:/var/log/nginx/
            - .:/var/www
        depends_on:
            - app

    mariadb:
        image: mariadb:latest
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: pizza_usr
            MARIADB_PASSWORD: pizza_password
            MARIADB_DATABASE: pizza

    phpmyadmin:
        image: phpmyadmin:latest
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mariadb
            PMA_USER: pizza_usr
            PMA_PASSWORD: pizza_password

    redis:
        image: redis:latest
        restart: unless-stopped
        ports:
            - "6379:6379"
        command: redis-server --requirepass root

    app:
        container_name: pizza-app
        build: .docker/php-fpm
        restart: unless-stopped
        volumes:
            - .:/var/www
        environment:
            DB_HOST: mariadb
            DB_PORT: 3306
            DB_DATABASE: pizza
            DB_USERNAME: pizza_usr
            DB_PASSWORD: pizza_password

            REDIS_HOST: redis
            REDIS_PASSWORD: root
            REDIS_PORT: 6379
        depends_on:
            - redis
            - mariadb
