openapi: 3.0.0
info:
  title: PizzaAPI
  version: 1.0.0
servers:
  - url: http://localhost
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    apikeyAuth:
      type: http
      scheme: apikey
security:
  - apikeyAuth: []
paths:
  /api/v1/orders:
    get:
      tags:
        - default
      summary: Получить список заказов
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                - order_id: abc123
                  done: false
                - order_id: ab12
                  done: true
    post:
      tags:
        - default
      summary: Создать заказ
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                items:
                  - 1
                  - 2
                  - 3
      security:
        - noauthAuth: []
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                order_id: abc123
                items:
                  - 1
                  - 2
                  - 3
                done: false
  /api/v1/orders/{order_id}:
    get:
      tags:
        - default
      summary: Получить информацию по заказу
      security:
        - noauthAuth: []
      parameters:
        - name: order_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                order_id: abc123
                items:
                  - 1
                  - 2
                  - 3
                done: false
  /api/v1/orders/{order_id}/items:
    post:
      tags:
        - default
      summary: Добавить товары в заказ
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                items:
                  - 1
      security:
        - noauthAuth: []
      parameters:
        - name: order_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                success: true
  /api/v1/orders/{order_id}/done:
    post:
      tags:
        - default
      summary: Установить статус заказа - готов
      requestBody:
        content: {}
      parameters:
        - name: order_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                success: true
